### ISSUE TITLE
Logger level for user credentials

### ISSUE THREAD

**Issue by playerjamesbattleground** [dirk-olmes/mule-transport-cifs#4]
Hi,

We are very happy that this lib helps us to easily transporting file with smb protocol. Only one enhancement requirement:

Currently the logger is logging the user credentials in plain text:
https://github.com/dirk-olmes/mule-transport-cifs/blob/master/src/main/java/org/mule/transport/cifs/SmbConnector.java#L164

Could this be DEBUG so that we can keep the secret? We can configure the log4j from our side but still like the source code to be updated in this case.

Regards
James

**Comment by dirk-olmes** [comment]
James, I've reviewed all uses of the passord in the connector and shared it when printing. This is in line with what the other Mule connectors do.

**Comment by playerjamesbattleground** [comment]
Hi Dirk,
Sorry to reply this late, thanks very much for the quick updates. I am happy to close this issue.

Regards
James
